'use strict';
const $=id=>document.getElementById(id),stems='甲乙丙丁戊己庚辛壬癸',branches='子丑寅卯辰巳午未申酉戌亥',sKo='갑을병정무기경신임계',bKo='자축인묘진사오미신유술해',names=['목','화','토','금','수'],colors=['#80caa1','#ee947d','#ebc384','#c5c4e6','#83b9ec'],traits=['새로운 일을 시작하고 키워 가는 모습','열정을 표현하고 주변을 밝히는 모습','중심을 잡고 차분히 돌보는 모습','기준을 세우고 다듬어 가는 모습','흐름에 맞춰 생각을 넓히는 모습'];
const se=ch=>Math.floor(stems.indexOf(ch)/2),be=ch=>[4,2,0,0,2,1,1,2,3,3,2,4][branches.indexOf(ch)];
$('calendar').addEventListener('change',()=>{$('leap-wrap').hidden=$('calendar').value!=='lunar'});
$('unknown').addEventListener('change',()=>{$('time').disabled=$('unknown').checked});
$('form').addEventListener('submit',e=>{e.preventDefault();$('error').textContent='';$('result').hidden=true;try{
 if(typeof Solar==='undefined'||typeof Lunar==='undefined')throw Error('계산 파일을 불러오지 못했습니다. 파일 세 개를 같은 폴더에 올려 주세요.');
 const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec($('birth').value);if(!match)throw Error('생년월일을 입력해 주세요.');const y=+match[1],m=+match[2],d=+match[3];if(y<1900||y>2099)throw Error('1900년부터 2099년까지 입력해 주세요.');const unknown=$('unknown').checked,time=unknown?'12:00':$('time').value;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('태어난 시각을 확인해 주세요.');const [h,min]=time.split(':').map(Number);let lunar,solar;
 if($('calendar').value==='solar'){const date=new Date(Date.UTC(y,m-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw Error('존재하지 않는 양력 날짜입니다.');solar=Solar.fromYmdHms(y,m,d,h,min,0);lunar=solar.getLunar()}
 else{if(m<1||m>12||d<1||d>30)throw Error('음력 날짜를 확인해 주세요.');const lm=$('leap').value==='yes'?-m:m;lunar=Lunar.fromYmdHms(y,lm,d,h,min,0);if(lunar.getYear()!==y||lunar.getMonth()!==lm||lunar.getDay()!==d)throw Error('해당 음력 날짜나 윤달이 존재하지 않습니다.');solar=lunar.getSolar();const back=solar.getLunar();if(back.getYear()!==y||back.getMonth()!==lm||back.getDay()!==d)throw Error('해당 음력 날짜나 윤달이 존재하지 않습니다.')}
 const ec=lunar.getEightChar();ec.setSect(2);const vals=[ec.getYear(),ec.getMonth(),ec.getDay(),unknown?null:ec.getTime()],labels=['연주','월주','일주','시주'];$('pillars').replaceChildren(...vals.map((v,i)=>{const box=document.createElement('div');box.className='pillar';const a=document.createElement('strong');a.textContent=labels[i];const b=document.createElement('div');b.className='hanja';b.textContent=v||'—';const c=document.createElement('div');c.className='ko';c.textContent=v?sKo[stems.indexOf(v[0])]+bKo[branches.indexOf(v[1])]:'시각 미상';box.append(a,b,c);return box}));
 $('date-label').textContent=`양력 ${solar.getYear()}.${String(solar.getMonth()).padStart(2,'0')}.${String(solar.getDay()).padStart(2,'0')}`;$('boundary-note').textContent=unknown?'시각 미상: 정오로 연·월·일주를 계산했습니다. 절입 당일이나 23시 부근에는 정확한 시각이 필요합니다.':'절입·23시 부근에는 출생지와 계산 방식에 따라 다른 결과가 나올 수 있습니다.';
 const counts=[0,0,0,0,0];vals.filter(Boolean).forEach(v=>{counts[se(v[0])]++;counts[be(v[1])]++});$('bars').replaceChildren(...counts.map((n,i)=>{const row=document.createElement('div');row.className='row';const a=document.createElement('strong');a.textContent=names[i];const track=document.createElement('div');track.className='track';const fill=document.createElement('div');fill.className='fill';fill.style.width=`${n/8*100}%`;fill.style.background=colors[i];track.append(fill);const b=document.createElement('span');b.textContent=n;row.append(a,track,b);return row}));const i=se(vals[2][0]);$('interpret').replaceChildren();const a=document.createElement('strong');a.textContent=`나를 상징하는 일간: ${sKo[stems.indexOf(vals[2][0])]}(${vals[2][0]}) · ${names[i]}`;const b=document.createElement('p');b.textContent=`전통 명리에서는 ${names[i]}을(를) ‘${traits[i]}’에 비유합니다. 내게 익숙한 모습인지 생각해 보세요.`;const c=document.createElement('p');c.className='small';c.textContent='상징적 비유이며 개인의 성향이나 미래를 판정하지 않습니다.';$('interpret').append(a,b,c);$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth',block:'start'});
 }catch(err){$('error').textContent=err?.message||'계산 중 오류가 났습니다. 입력을 확인해 주세요.'}});
